packages:
  - "packages/**"

# 30 days
minimumReleaseAge: 43200
minimumReleaseAgeExclude:
  - rolldown
  - "@rolldown/pluginutils"
  - "@oxc-project/types"
  - "@rolldown/binding-darwin-x64"
  - "@rolldown/binding-win32-x64-msvc"
  - "@rolldown/binding-linux-x64-gnu"
  - "@rolldown/binding-linux-x64-musl"
  - "@rolldown/binding-freebsd-x64"
  - "@rolldown/binding-win32-ia32-msvc"
  - "@rolldown/binding-linux-arm-gnueabihf"
  - "@rolldown/binding-linux-arm64-gnu"
  - "@rolldown/binding-darwin-arm64"
  - "@rolldown/binding-linux-arm64-musl"
  - "@rolldown/binding-openharmony-arm64"
  - "@rolldown/binding-win32-arm64-msvc"
  - "@rolldown/binding-android-arm64"
  - "@rolldown/binding-wasm32-wasi"
