packages:
  - "packages/**"

catalog:
  prettier: 3.6.2
  depcheck: 1.4.7
  eslint: 8.57.1
  eslint-plugin-jest: 29.0.1
  eslint-config-prettier: 10.1.8
  "@types/jest": 29.5.14
  jest: 29.7.0
  ts-jest: 29.4.5
  typescript: 5.9.3
  lodash: 4.17.21
  "@types/lodash": 4.17.20
  "@tsconfig/node12": 12.1.5
  "@tsconfig/node16": 16.1.5
  "@tsconfig/node18": 18.2.4
  "@typescript-eslint/eslint-plugin": 8.47.0
  "@typescript-eslint/parser": 8.47.0

minimumReleaseAge: 43200 # 30 days
minimumReleaseAgeExclude:
  - rolldown
  - "@oxc-project/*"
  - "@rolldown/*"
  - "@typescript-eslint/*"
